/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Harbors/HarborModel.model.json
    code gen version  = 5
    model version     = 4

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;
using Catan3.Utility;

namespace Catan3.Models
{
    public partial class HarborModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private HexCoordinates _tileCoordinates = new (0,0,0);
        public HexCoordinates TileCoordinates
         {
            get => _tileCoordinates;
            set
            {
                if (Equals(value, _tileCoordinates)) return;
                _tileCoordinates = value;
                OnPropertyChanged(nameof(TileCoordinates));
             }
         }

        private HarborType _harborType = HarborType.ThreeForOne;
        public HarborType HarborType
         {
            get => _harborType;
            set
            {
                if (Equals(value, _harborType)) return;
                _harborType = value;
                OnPropertyChanged(nameof(HarborType));
             }
         }

        private HexSide _position = HexSide.Bottom;
        public HexSide Position
         {
            get => _position;
            set
            {
                if (Equals(value, _position)) return;
                _position = value;
                OnPropertyChanged(nameof(Position));
             }
         }

        private PlayerModel? _owner = null;
        public PlayerModel? Owner
         {
            get => _owner;
            set
            {
                if (Equals(value, _owner)) return;
                _owner = value;
                OnPropertyChanged(nameof(Owner));
             }
         }


        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
