/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/ResourceCard/ResourceCard.model.json
    code gen version  = 5
    model version     = 2

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;
using Microsoft.UI.Xaml;

namespace Catan3.Models
{
    public partial class ResourceCardModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private ResourceCardType _resourceType = ResourceCardType.None;
        public ResourceCardType ResourceType
         {
            get => _resourceType;
            set
            {
                if (Equals(value, _resourceType)) return;
                _resourceType = value;
                OnPropertyChanged(nameof(ResourceType));
             }
         }

        private int _count = 0;
        public int Count
         {
            get => _count;
            set
            {
                if (Equals(value, _count)) return;
                _count = value;
                OnPropertyChanged(nameof(Count));
             }
         }

        private CatanOrientation _orientation = CatanOrientation.FaceDown;
        public CatanOrientation Orientation
         {
            get => _orientation;
            set
            {
                if (Equals(value, _orientation)) return;
                _orientation = value;
                OnPropertyChanged(nameof(Orientation));
             }
         }

        private Visibility _countVisibility = Visibility.Visible;
        public Visibility CountVisibility
         {
            get => _countVisibility;
            set
            {
                if (Equals(value, _countVisibility)) return;
                _countVisibility = value;
                OnPropertyChanged(nameof(CountVisibility));
             }
         }


        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
