/* WARNING: this is an autogenerated file.  Do Not edit directly.  Edit the /Models/models.json file instead */
using System.ComponentModel;
namespace Catan3.Models
{
    public partial class PersonModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
