/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Game/GameModel.model.json
    code gen version  = 5
    model version     = 8

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.Collections.ObjectModel;
using System.ComponentModel;
using Catan3.Utility;

namespace Catan3.Models
{
    public partial class GameModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private CatanGame _gameType = CatanGame.Regular;
        public CatanGame GameType
         {
            get => _gameType;
            set
            {
                if (Equals(value, _gameType)) return;
                _gameType = value;
                OnPropertyChanged(nameof(GameType));
             }
         }

        private bool _hasSupplementalBuildPhase = false;
        public bool HasSupplementalBuildPhase
         {
            get => _hasSupplementalBuildPhase;
            set
            {
                if (Equals(value, _hasSupplementalBuildPhase)) return;
                _hasSupplementalBuildPhase = value;
                OnPropertyChanged(nameof(HasSupplementalBuildPhase));
             }
         }

        private ObservableCollection<TileModel> _tiles = [];
        public ObservableCollection<TileModel> Tiles
         {
            get => _tiles;
            set
            {
                if (Equals(value, _tiles)) return;
                _tiles = value;
                OnPropertyChanged(nameof(Tiles));
             }
         }

        private ObservableCollection<BuildingModel> _buildings = [];
        public ObservableCollection<BuildingModel> Buildings
         {
            get => _buildings;
            set
            {
                if (Equals(value, _buildings)) return;
                _buildings = value;
                OnPropertyChanged(nameof(Buildings));
             }
         }

        private ObservableCollection<PlayerModel> _players = [];
        public ObservableCollection<PlayerModel> Players
         {
            get => _players;
            set
            {
                if (Equals(value, _players)) return;
                _players = value;
                OnPropertyChanged(nameof(Players));
             }
         }

        private ObservableCollection<RoadModel> _roads = [];
        public ObservableCollection<RoadModel> Roads
         {
            get => _roads;
            set
            {
                if (Equals(value, _roads)) return;
                _roads = value;
                OnPropertyChanged(nameof(Roads));
             }
         }

        private ObservableCollection<HarborModel> _harbors = [];
        public ObservableCollection<HarborModel> Harbors
         {
            get => _harbors;
            set
            {
                if (Equals(value, _harbors)) return;
                _harbors = value;
                OnPropertyChanged(nameof(Harbors));
             }
         }

        private RobberModel _robber = new();
        public RobberModel Robber
         {
            get => _robber;
            set
            {
                if (Equals(value, _robber)) return;
                _robber = value;
                OnPropertyChanged(nameof(Robber));
             }
         }


        public GameModel(CatanGame gametype, bool hassupplementalbuildphase)
        {
            _gameType = gametype;
            _hasSupplementalBuildPhase = hassupplementalbuildphase;
        }

        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
