/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Game/GameViewModel.model.json
    code gen version  = 5
    model version     = 3

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.Collections.ObjectModel;
using System.ComponentModel;
using Catan3.Utility;

namespace Catan3.Models
{
    public partial class GameViewModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private IBoardInfo? _boardInfo;
        public IBoardInfo? BoardInfo
         {
            get => _boardInfo;
            set
            {
                if (Equals(value, _boardInfo)) return;
                _boardInfo = value;
                OnPropertyChanged(nameof(BoardInfo));
             }
         }

        private RobberViewModel _robber = new(new());
        public RobberViewModel Robber
         {
            get => _robber;
            set
            {
                if (Equals(value, _robber)) return;
                _robber = value;
                OnPropertyChanged(nameof(Robber));
             }
         }

        private string _name = "Nameless";
        public string Name
         {
            get => _name;
            set
            {
                if (Equals(value, _name)) return;
                _name = value;
                OnPropertyChanged(nameof(Name));
             }
         }

        private bool _isKnightsAndRobbers = false;
        public bool IsKnightsAndRobbers
         {
            get => _isKnightsAndRobbers;
            set
            {
                if (Equals(value, _isKnightsAndRobbers)) return;
                _isKnightsAndRobbers = value;
                OnPropertyChanged(nameof(IsKnightsAndRobbers));
             }
         }

        private HouseRules _houseRules = new HouseRules();
        public HouseRules HouseRules
         {
            get => _houseRules;
            set
            {
                if (Equals(value, _houseRules)) return;
                _houseRules = value;
                OnPropertyChanged(nameof(HouseRules));
             }
         }

        private PlayerViewModel? _currentPlayer;
        public PlayerViewModel? CurrentPlayer
         {
            get => _currentPlayer;
            set
            {
                if (Equals(value, _currentPlayer)) return;
                _currentPlayer = value;
                OnPropertyChanged(nameof(CurrentPlayer));
             }
         }

        private ObservableCollection<TileViewModel> _tiles = [];
        public ObservableCollection<TileViewModel> Tiles
         {
            get => _tiles;
            set
            {
                if (Equals(value, _tiles)) return;
                _tiles = value;
                OnPropertyChanged(nameof(Tiles));
             }
         }

        private ObservableCollection<BuildingViewModel> _buildings = [];
        public ObservableCollection<BuildingViewModel> Buildings
         {
            get => _buildings;
            set
            {
                if (Equals(value, _buildings)) return;
                _buildings = value;
                OnPropertyChanged(nameof(Buildings));
             }
         }

        private ObservableCollection<PlayerViewModel> _players = [];
        public ObservableCollection<PlayerViewModel> Players
         {
            get => _players;
            set
            {
                if (Equals(value, _players)) return;
                _players = value;
                OnPropertyChanged(nameof(Players));
             }
         }

        private ObservableCollection<RoadViewModel> _roads = [];
        public ObservableCollection<RoadViewModel> Roads
         {
            get => _roads;
            set
            {
                if (Equals(value, _roads)) return;
                _roads = value;
                OnPropertyChanged(nameof(Roads));
             }
         }

        private ObservableCollection<HarborViewModel> _harbors = [];
        public ObservableCollection<HarborViewModel> Harbors
         {
            get => _harbors;
            set
            {
                if (Equals(value, _harbors)) return;
                _harbors = value;
                OnPropertyChanged(nameof(Harbors));
             }
         }


        public GameViewModel(IBoardInfo? boardinfo)
        {
            _boardInfo = boardinfo;
        }

        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
