/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Game/HouseRules.model.json
    code gen version  = 5
    model version     = 1.0

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;

namespace Catan3.Models
{
    public partial class HouseRules : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private int _goldTiles = 1;
        public int GoldTiles
         {
            get => _goldTiles;
            set
            {
                if (Equals(value, _goldTiles)) return;
                _goldTiles = value;
                OnPropertyChanged(nameof(GoldTiles));
             }
         }

        private bool _wallsProtectCities = true;
        public bool WallsProtectCities
         {
            get => _wallsProtectCities;
            set
            {
                if (Equals(value, _wallsProtectCities)) return;
                _wallsProtectCities = value;
                OnPropertyChanged(nameof(WallsProtectCities));
             }
         }

        private bool _hideBaronBeforeInvasion = false;
        public bool HideBaronBeforeInvasion
         {
            get => _hideBaronBeforeInvasion;
            set
            {
                if (Equals(value, _hideBaronBeforeInvasion)) return;
                _hideBaronBeforeInvasion = value;
                OnPropertyChanged(nameof(HideBaronBeforeInvasion));
             }
         }

        private bool _knightMovesBaronBeforeRoll = true;
        public bool KnightMovesBaronBeforeRoll
         {
            get => _knightMovesBaronBeforeRoll;
            set
            {
                if (Equals(value, _knightMovesBaronBeforeRoll)) return;
                _knightMovesBaronBeforeRoll = value;
                OnPropertyChanged(nameof(KnightMovesBaronBeforeRoll));
             }
         }


        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
