<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>Catan3</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win10-$(Platform).pubxml</PublishProfile>
		<UseWinUI>true</UseWinUI>
		<EnableMsixTooling>true</EnableMsixTooling>
		<Nullable>enable</Nullable>
		<SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>
		<StartupObject></StartupObject>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="Controls\BuildingCtrl.xaml" />
		<None Remove="Controls\GameBoardCtrl.xaml" />
		<None Remove="Controls\RoadCtrl.xaml" />
		<None Remove="Controls\TileCtrl.xaml" />
		<None Remove="FlipperCtrl.xaml" />
		<None Remove="GameButtons.xaml" />
		<None Remove="Game\Game Control\GameControls.xaml" />
		<None Remove="Harbors\HarborCtrl.xaml" />
		<None Remove="MainPage.xaml" />
		<None Remove="ResourceCard\BoardMeasurementCtrl.xaml" />
		<None Remove="ResourceCard\ResourceCardCtrl.xaml" />
		<None Remove="Themes\Generic.xaml" />
		<None Remove="Themes\ImageResources.xaml" />
		<None Remove="Themes\StyleResourceDictionary.xaml" />
		<None Remove="Themes\Styles.xaml" />
		<None Remove="ValueConverters\ConverterDictionary.xaml" />
	</ItemGroup>
	<ItemGroup>
	  <Page Remove="Themes\Styles.xaml" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\SplashScreen.scale-200.png" />
		<Content Include="Assets\LockScreenLogo.scale-200.png" />
		<Content Include="Assets\Square150x150Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.scale-200.png" />
		<Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
		<Content Include="Assets\Wide310x150Logo.scale-200.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
		<PackageReference Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.5.240404000" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.3233" />
		<PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
		<PackageReference Include="System.Text.Json" Version="8.0.3" />
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<!-- 
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Harbors\HarborCtrl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="FlipperCtrl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="GameButtons.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="Game\Game Control\GameControls.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <None Update="GenerateModels.tt">
	    <Generator>TextTemplatingFileGenerator</Generator>
	    <LastGenOutput>GenerateModels.txt</LastGenOutput>
	  </None>
	  <None Update="GenerateModels.txt">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>GenerateModels.tt</DependentUpon>
	  </None>
	  <None Update="Models\ModelGeneration\models.tt">
	    <Generator>TextTemplatingFileGenerator</Generator>
	    <LastGenOutput>models.cs</LastGenOutput>
	  </None>
	  <Page Update="Tiles\CatanNumber.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="ValueConverters\ConverterDictionary.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="Themes\ImageResources.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="Themes\StyleResourceDictionary.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="Themes\Generic.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="ResourceCard\BoardMeasurementCtrl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	  <Page Update="ResourceCard\ResourceCardCtrl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\TileCtrl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\RoadCtrl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
	  <Page Update="Controls\GameBoardCtrl.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="MainPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Controls\BuildingCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
	  <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Update="Models\ModelGeneration\models.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>models.tt</DependentUpon>
	  </Compile>
	</ItemGroup>

	<!-- 
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution 
    Explorer "Package and Publish" context menu entry to be enabled for this project even if 
    the Windows App SDK Nuget package has not yet been restored.
  -->
	<PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
	
	</PropertyGroup>
	<ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>
</Project>
