<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<LangVersion>preview</LangVersion>
		<RootNamespace>Catan3</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<PublishProfile>win10-$(Platform).pubxml</PublishProfile>
		<UseWinUI>true</UseWinUI>
		<EnableMsixTooling>true</EnableMsixTooling>
		<Nullable>enable</Nullable>
		<SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>
		<StartupObject></StartupObject>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Player\PlayerOrder\**" />
		<EmbeddedResource Remove="Player\PlayerOrder\**" />
		<None Remove="Player\PlayerOrder\**" />
		<Page Remove="Player\PlayerOrder\**" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="Player\PlayerOrderModel.cs" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="Assets\AppIcon.png" />
		<None Remove="Assets\Test Files\Score Test.catan" />
		<None Remove="Buildings\BuildingCtrl.xaml" />
		<None Remove="Controls\PurchaseCtrl.xaml" />
		<None Remove="Game\Game Control\GameControls.xaml" />
		<None Remove="Game\GameFactory\GameBoardCtrl.xaml" />
		<None Remove="Game\NewGame\NewGamePage.xaml" />
		<None Remove="MainPage\MainPage.xaml" />
		<None Remove="MainPage\MainWindow.xaml" />
		<None Remove="Player\PlayerSettingDlg.xaml" />
		<None Remove="Player\PlayerSettingsCtrl.xaml" />
		<None Remove="Player\PlayerSettings\PlayerEditorPage.xaml" />
		<None Remove="Player\PlayerSettings\PlayerEditorWindow.xaml" />
		<None Remove="Player\PlayerSettings\PlayerSettingsCtrl.xaml" />
		<None Remove="Player\SetPlayerOrderCtrl.xaml" />
		<None Remove="Resources\BoardMeasurementCtrl.xaml" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="CommunityToolkit.WinUI" Version="7.1.2" />
		<PackageReference Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />
		<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.3.1" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.241114003" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="2.0.9" />
		<PackageReference Include="System.Text.Encodings.Web" Version="9.0.0" />
		<PackageReference Include="System.Text.Json" Version="9.0.0" />
		<PackageReference Include="WinUIEx" Version="2.5.0" />
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>
	<!-- 
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>
	<ItemGroup>
		<Page Update="Harbors\HarborCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Utility\FlipperCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>

		<Page Update="Player\PlayerEditorWindow.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Player\PlayerEditorPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Resources\TrackedResourcesCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Player\PlayerCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Player\PlayerCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Rolls\SingleRoll.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Tiles\CatanNumber.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="ValueConverters\ConverterDictionary.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Themes\ImageResources.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Themes\StyleResourceDictionary.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Themes\Generic.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="ResourceCard\BoardMeasurementCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="ResourceCard\ResourceCardCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Tiles\TileCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Roads\RoadCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>


	<ItemGroup>
		<Resource Include="Assets\cherry.jpg" />
		<Resource Include="Assets\LargeTile.scale-100.png" />
		<Resource Include="Assets\LargeTile.scale-125.png" />
		<Resource Include="Assets\LargeTile.scale-150.png" />
		<Resource Include="Assets\LargeTile.scale-200.png" />
		<Resource Include="Assets\LargeTile.scale-400.png" />
		<Resource Include="Assets\maple.jpg" />
		<Resource Include="Assets\SmallTile.scale-100.png" />
		<Resource Include="Assets\SmallTile.scale-125.png" />
		<Resource Include="Assets\SmallTile.scale-150.png" />
		<Resource Include="Assets\SmallTile.scale-200.png" />
		<Resource Include="Assets\SmallTile.scale-400.png" />
		<Resource Include="Assets\SplashScreen.scale-100.png" />
		<Resource Include="Assets\SplashScreen.scale-125.png" />
		<Resource Include="Assets\SplashScreen.scale-150.png" />
		<Resource Include="Assets\SplashScreen.scale-400.png" />
		<Resource Include="Assets\square 71x71 logo.scale-100.png" />
		<Resource Include="Assets\square 71x71 logo.scale-200.png" />
		<Resource Include="Assets\Square150x150Logo.scale-100.png" />
		<Resource Include="Assets\Square150x150Logo.scale-125.png" />
		<Resource Include="Assets\Square150x150Logo.scale-150.png" />
		<Resource Include="Assets\Square150x150Logo.scale-400.png" />
		<Resource Include="Assets\AppIcon.png" />
		<Resource Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-16.png" />
		<Resource Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-24.png" />
		<Resource Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-256.png" />
		<Resource Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-32.png" />
		<Resource Include="Assets\Square44x44Logo.altform-lightunplated_targetsize-48.png" />
		<Resource Include="Assets\Square44x44Logo.altform-unplated_targetsize-16.png" />
		<Resource Include="Assets\Square44x44Logo.altform-unplated_targetsize-256.png" />
		<Resource Include="Assets\Square44x44Logo.altform-unplated_targetsize-32.png" />
		<Resource Include="Assets\Square44x44Logo.altform-unplated_targetsize-48.png" />
		<Resource Include="Assets\Square44x44Logo.scale-100.png" />
		<Resource Include="Assets\Square44x44Logo.scale-125.png" />
		<Resource Include="Assets\Square44x44Logo.scale-150.png" />
		<Resource Include="Assets\Square44x44Logo.scale-400.png" />
		<Resource Include="Assets\Square44x44Logo.targetsize-16.png" />
		<Resource Include="Assets\Square44x44Logo.targetsize-24.png" />
		<Resource Include="Assets\Square44x44Logo.targetsize-256.png" />
		<Resource Include="Assets\Square44x44Logo.targetsize-32.png" />
		<Resource Include="Assets\Square44x44Logo.targetsize-48.png" />
		<Resource Include="Assets\StoreLogo.backup.png" />
		<Resource Include="Assets\StoreLogo.scale-100.png" />
		<Resource Include="Assets\StoreLogo.scale-125.png" />
		<Resource Include="Assets\StoreLogo.scale-150.png" />
		<Resource Include="Assets\StoreLogo.scale-200.png" />
		<Resource Include="Assets\StoreLogo.scale-400.png" />
		<Resource Include="Assets\water.png" />
		<Resource Include="Assets\Wide310x150Logo.scale-100.png" />
		<Resource Include="Assets\Wide310x150Logo.scale-125.png" />
		<Resource Include="Assets\Wide310x150Logo.scale-150.png" />
		<Resource Include="Assets\Wide310x150Logo.scale-400.png" />
	</ItemGroup>


	<ItemGroup>
		<Page Update="Player\SetPlayerOrderCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>


	<ItemGroup>
		<Page Update="Game\NewGameDlg\NewGameCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>


	<ItemGroup>
		<Page Update="MainPage\MainWindow.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>


	<ItemGroup>
		<Page Update="Player\PlayerSettings\PlayerEditorPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Player\PlayerSettings\PlayerEditorWindow.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Player\PlayerSettings\PlayerSettingsCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>


	<ItemGroup>
		<Page Update="Player\PlayerSettingsCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>


	<ItemGroup>
		<Page Update="MainPage\MainPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>


	<ItemGroup>
		<Page Update="Game\GameFactory\GameBoardCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>


	<ItemGroup>
		<Page Update="Buildings\BuildingCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Controls\PurchaseCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Game\Game Control\GameControls.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
		<Page Update="Player\PlayerSettingDlg.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>




	<!-- 
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution 
    Explorer "Package and Publish" context menu entry to be enabled for this project even if 
    the Windows App SDK Nuget package has not yet been restored.
  -->
	<PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>

	</PropertyGroup>
	<ProjectExtensions>
		<VisualStudio>
			<UserProperties />
		</VisualStudio>
	</ProjectExtensions>
	<ItemGroup>
		<PRIResource Remove="Player\PlayerOrder\**" />
	</ItemGroup>
	<ItemGroup>
		<Content Remove="Assets\AppIcon.png" />
		<Content Remove="Assets\Guest.png" />
	</ItemGroup>
	<ItemGroup>
		<Page Update="Resources\BoardMeasurementCtrl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Game\NewGame\NewGamePage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
</Project>
