/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Layout/BoardLayout.model.json
    code gen version  = 5
    model version     = 10

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System;
using System.ComponentModel;

namespace Catan3.Models
{
    public partial class BoardLayout : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private double _tileYOffset = 0;
        public double TileYOffset
         {
            get => _tileYOffset;
            set
            {
                if (Equals(value, _tileYOffset)) return;
                _tileYOffset = value;
                OnPropertyChanged(nameof(TileYOffset));
                OnPropertyChanged(nameof(BoardHeight));
                OnPropertyChanged(nameof(BoardWidth));
             }
         }

        private double _tileXOffset = 0;
        public double TileXOffset
         {
            get => _tileXOffset;
            set
            {
                if (Equals(value, _tileXOffset)) return;
                _tileXOffset = value;
                OnPropertyChanged(nameof(TileXOffset));
                OnPropertyChanged(nameof(BoardHeight));
                OnPropertyChanged(nameof(BoardWidth));
             }
         }

        private double _boardWidth = 500;
        public double BoardWidth
         {
            get => _boardWidth;
            set
            {
                if (Equals(value, _boardWidth)) return;
                _boardWidth = value;
                OnPropertyChanged(nameof(BoardWidth));
                OnPropertyChanged(nameof(BoardHeight));
                OnPropertyChanged(nameof(BoardWidth));
             }
         }

        private double _boardHeight = 500;
        public double BoardHeight
         {
            get => _boardHeight;
            set
            {
                if (Equals(value, _boardHeight)) return;
                _boardHeight = value;
                OnPropertyChanged(nameof(BoardHeight));
                OnPropertyChanged(nameof(BoardHeight));
                OnPropertyChanged(nameof(BoardWidth));
             }
         }

        private double _outerHexSize = 100.0;
        public double OuterHexSize
         {
            get => _outerHexSize;
            set
            {
                if (Equals(value, _outerHexSize)) return;
                _outerHexSize = value;
                OnPropertyChanged(nameof(OuterHexSize));
                OnPropertyChanged(nameof(ControlWidth));
                OnPropertyChanged(nameof(ControlHeight));
                OnPropertyChanged(nameof(BoardWidth));
                OnPropertyChanged(nameof(BoardHeight));
                OnPropertyChanged(nameof(InnerHexPoints));
                OnPropertyChanged(nameof(InnerHexSize));
                OnPropertyChanged(nameof(OuterHexPoints));
                OnPropertyChanged(nameof(PointyHexPoints));
             }
         }

        private double _innerHexStrokeThickness = 16.0;
        public double InnerHexStrokeThickness
         {
            get => _innerHexStrokeThickness;
            set
            {
                if (Equals(value, _innerHexStrokeThickness)) return;
                _innerHexStrokeThickness = value;
                OnPropertyChanged(nameof(InnerHexStrokeThickness));
                OnPropertyChanged(nameof(InnerHexPoints));
                OnPropertyChanged(nameof(InnerHexSize));
             }
         }

        private double _outerHexStrokeThickness = 0.0;
        public double OuterHexStrokeThickness
         {
            get => _outerHexStrokeThickness;
            set
            {
                if (Equals(value, _outerHexStrokeThickness)) return;
                _outerHexStrokeThickness = value;
                OnPropertyChanged(nameof(OuterHexStrokeThickness));
                OnPropertyChanged(nameof(OuterHexPoints));
                OnPropertyChanged(nameof(OuterHexSize));
             }
         }

        private double _tileGap = 2;
        public double TileGap
         {
            get => _tileGap;
            set
            {
                if (Equals(value, _tileGap)) return;
                _tileGap = value;
                OnPropertyChanged(nameof(TileGap));
                OnPropertyChanged(nameof(InnerHexPoints));
                OnPropertyChanged(nameof(InnerHexSize));
             }
         }

        private double _gameMargin = 7.0;
        public double GameMargin
         {
            get => _gameMargin;
            set
            {
                if (Equals(value, _gameMargin)) return;
                _gameMargin = value;
                OnPropertyChanged(nameof(GameMargin));
                OnPropertyChanged(nameof(BoardWidth));
                OnPropertyChanged(nameof(BoardHeight));
             }
         }

        private double _buildingSize = 40;
        public double BuildingSize
         {
            get => _buildingSize;
            set
            {
                if (Equals(value, _buildingSize)) return;
                _buildingSize = value;
                OnPropertyChanged(nameof(BuildingSize));
                OnPropertyChanged(nameof(BoardWidth));
                OnPropertyChanged(nameof(BoardHeight));
                OnPropertyChanged(nameof(OuterHexPoints));
             }
         }

        private double _roadStrokeThickness = 2.0;
        public double RoadStrokeThickness
         {
            get => _roadStrokeThickness;
            set
            {
                if (Equals(value, _roadStrokeThickness)) return;
                _roadStrokeThickness = value;
                OnPropertyChanged(nameof(RoadStrokeThickness));
             }
         }

        private double _layoutGuideStrokeWidth = 0.0;
        public double LayoutGuideStrokeWidth
         {
            get => _layoutGuideStrokeWidth;
            set
            {
                if (Equals(value, _layoutGuideStrokeWidth)) return;
                _layoutGuideStrokeWidth = value;
                OnPropertyChanged(nameof(LayoutGuideStrokeWidth));
             }
         }


        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
