/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Layout/BoardLayout.model.json
    code gen version  = 5
    model version     = 9

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System;
using System.ComponentModel;

namespace Catan3.Models
{
    public partial class BoardLayout : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private int _rowCount = 5;
        public int RowCount
         {
            get => _rowCount;
            set
            {
                if (Equals(value, _rowCount)) return;
                _rowCount = value;
                OnPropertyChanged(nameof(RowCount));
                OnPropertyChanged(nameof(BoardHeight));
                OnPropertyChanged(nameof(BoardWidth));
             }
         }

        private double _columnOffset = 1.5; //the number of Size's to the .Left of the control;
        public double ColumnOffset
         {
            get => _columnOffset;
            set
            {
                if (Equals(value, _columnOffset)) return;
                _columnOffset = value;
                OnPropertyChanged(nameof(ColumnOffset));
                OnPropertyChanged(nameof(BoardHeight));
                OnPropertyChanged(nameof(BoardWidth));
             }
         }

        private double _outerHexSize = 100.0;
        public double OuterHexSize
         {
            get => _outerHexSize;
            set
            {
                if (Equals(value, _outerHexSize)) return;
                _outerHexSize = value;
                OnPropertyChanged(nameof(OuterHexSize));
                OnPropertyChanged(nameof(ControlWidth));
                OnPropertyChanged(nameof(ControlHeight));
                OnPropertyChanged(nameof(BoardWidth));
                OnPropertyChanged(nameof(BoardHeight));
                OnPropertyChanged(nameof(InnerHexPoints));
                OnPropertyChanged(nameof(InnerHexSize));
                OnPropertyChanged(nameof(OuterHexPoints));
                OnPropertyChanged(nameof(PointyHexPoints));
             }
         }

        private double _innerHexStrokeThickness = 5.0;
        public double InnerHexStrokeThickness
         {
            get => _innerHexStrokeThickness;
            set
            {
                if (Equals(value, _innerHexStrokeThickness)) return;
                _innerHexStrokeThickness = value;
                OnPropertyChanged(nameof(InnerHexStrokeThickness));
                OnPropertyChanged(nameof(InnerHexPoints));
                OnPropertyChanged(nameof(InnerHexSize));
             }
         }

        private double _outerHexStrokeThickness = 0.0;
        public double OuterHexStrokeThickness
         {
            get => _outerHexStrokeThickness;
            set
            {
                if (Equals(value, _outerHexStrokeThickness)) return;
                _outerHexStrokeThickness = value;
                OnPropertyChanged(nameof(OuterHexStrokeThickness));
                OnPropertyChanged(nameof(OuterHexPoints));
                OnPropertyChanged(nameof(OuterHexSize));
             }
         }

        private double _tileGap = 5;
        public double TileGap
         {
            get => _tileGap;
            set
            {
                if (Equals(value, _tileGap)) return;
                _tileGap = value;
                OnPropertyChanged(nameof(TileGap));
                OnPropertyChanged(nameof(InnerHexPoints));
                OnPropertyChanged(nameof(InnerHexSize));
             }
         }

        private double _gameMargin = 7.0;
        public double GameMargin
         {
            get => _gameMargin;
            set
            {
                if (Equals(value, _gameMargin)) return;
                _gameMargin = value;
                OnPropertyChanged(nameof(GameMargin));
                OnPropertyChanged(nameof(BoardWidth));
                OnPropertyChanged(nameof(BoardHeight));
             }
         }

        private double _buildingSize = 40;
        public double BuildingSize
         {
            get => _buildingSize;
            set
            {
                if (Equals(value, _buildingSize)) return;
                _buildingSize = value;
                OnPropertyChanged(nameof(BuildingSize));
                OnPropertyChanged(nameof(BoardWidth));
                OnPropertyChanged(nameof(BoardHeight));
                OnPropertyChanged(nameof(OuterHexPoints));
             }
         }

        private double _roadStrokeThickness = 2.0;
        public double RoadStrokeThickness
         {
            get => _roadStrokeThickness;
            set
            {
                if (Equals(value, _roadStrokeThickness)) return;
                _roadStrokeThickness = value;
                OnPropertyChanged(nameof(RoadStrokeThickness));
             }
         }

        private double _layoutGuideStrokeWidth = 0.0;
        public double LayoutGuideStrokeWidth
         {
            get => _layoutGuideStrokeWidth;
            set
            {
                if (Equals(value, _layoutGuideStrokeWidth)) return;
                _layoutGuideStrokeWidth = value;
                OnPropertyChanged(nameof(LayoutGuideStrokeWidth));
             }
         }


        public BoardLayout(int rowcount, double columnoffset)
        {
            _rowCount = rowcount;
            _columnOffset = columnoffset;
        }

        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
