/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Layout/HexCoordinates.model.json
    code gen version  = 5
    model version     = 2

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;

namespace Catan3.Utility
{
    public partial class HexCoordinates : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private int _q = q;
        public int Q
         {
            get => _q;
            set
            {
                if (Equals(value, _q)) return;
                _q = value;
                OnPropertyChanged(nameof(Q));
             }
         }

        private int _r = r;
        public int R
         {
            get => _r;
            set
            {
                if (Equals(value, _r)) return;
                _r = value;
                OnPropertyChanged(nameof(R));
             }
         }

        private int _s = s;
        public int S
         {
            get => _s;
            set
            {
                if (Equals(value, _s)) return;
                _s = value;
                OnPropertyChanged(nameof(S));
             }
         }


        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
