
using System.Collections.Generic;
using Catan10.Models;
using CommunityToolkit.Mvvm.ComponentModel;
using System.Linq;
using System.Collections.ObjectModel;
namespace Catan3.Models
{
    /// <summary>
    ///     this should have all the data representing per player state that is bound to the UI 
    /// </summary>
    /// <param name="idx"></param>
    public partial class PlayerModel : ObservableObject
    {
        [ObservableProperty]
        private string _id ;
        [ObservableProperty]
        private int _goldRolls = 0;
        [ObservableProperty]
        private int _goodRolls = 0;
        [ObservableProperty]
        private int _badRolls = 0;
        [ObservableProperty]
        private bool _hasLongestRoad = false;
        [ObservableProperty]
        private int _islandsPlayed;
        [ObservableProperty]
        private bool _largestArmy = false;
        [ObservableProperty]
        private int _longestRoad;
        [ObservableProperty]
        private int _maxNoResourceRolls = 0;
        [ObservableProperty]
        private int _noResourceCount = 0;
        [ObservableProperty]
        private int _stars = 0;
        [ObservableProperty]
        private int _score;
        [ObservableProperty]
        private bool  _highestScore = false;
        [ObservableProperty]
        private int _timesTargeted;
        [ObservableProperty]
        private bool _participatingInSupplemental;
        /// <summary>
        ///  how many resources did the player get this turn?  re-created when the
        ///  GameState transitions to WaitingForRoll
        /// </summary>
        [ObservableProperty]
        private ResourcesModel _resourcesThisTurn = new();
        /// <summary>
        /// /   aggregate value of all resources generated by this player
        /// </summary>
        [ObservableProperty]
        private ResourcesModel _resourcesThisGame = new();
        [ObservableProperty]
        private ObservableCollection<Entitlement> _unspentEntitlements = [];
        [ObservableProperty]
        private ObservableCollection<Entitlement> _spentEntitlementsThisGame = [];
        [ObservableProperty]
        private ObservableCollection<Entitlement> _spentEntitlementsThisTurn = [];
        public static PlayerModel Default { get; } = new PlayerModel("Nameless-001");
        private PlayerModel() { Id = "Nameless-002"; }
        public PlayerModel(string id)
        {
            Id = id;
        }
        public override string ToString()
        {
            return $"{Id}";
        }
    }
    public static class PlayerModelExtensions
    {
        public static PlayerModel? PlayerFromId(this IList<PlayerModel> collection, string id)
        {
            return collection.FirstOrDefault((p) => p.Id == id);
        }
    }
}
