/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Player/PlayerViewModel.model.json
    code gen version  = 5
    model version     = 1.0

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;
using Windows.UI;

namespace Catan3.Models
{
    public partial class PlayerViewModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private string _id = string.Empty;
        public string Id
         {
            get => _id;
            set
            {
                if (Equals(value, _id)) return;
                _id = value;
                OnPropertyChanged(nameof(Id));
             }
         }

        private string _name = name;
        public string Name
         {
            get => _name;
            set
            {
                if (Equals(value, _name)) return;
                _name = value;
                OnPropertyChanged(nameof(Name));
             }
         }

        private Color _foreground = foreground;
        public Color Foreground
         {
            get => _foreground;
            set
            {
                if (Equals(value, _foreground)) return;
                _foreground = value;
                OnPropertyChanged(nameof(Foreground));
             }
         }

        private Color _background = background;
        public Color Background
         {
            get => _background;
            set
            {
                if (Equals(value, _background)) return;
                _background = value;
                OnPropertyChanged(nameof(Background));
             }
         }

        private string _imageFileName = "ms-appx:///Assets/guest.jpg";
        public string ImageFileName
         {
            get => _imageFileName;
            set
            {
                if (Equals(value, _imageFileName)) return;
                _imageFileName = value;
                OnPropertyChanged(nameof(ImageFileName));
             }
         }

        private PlayerModel _player = PlayerModel.Default;
        public PlayerModel Player
         {
            get => _player;
            set
            {
                if (Equals(value, _player)) return;
                _player = value;
                OnPropertyChanged(nameof(Player));
             }
         }


        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
