/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Player/PlayerModel.model.json
    code gen version  = 5
    model version     = 1.0

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;

namespace Catan3.Models
{
    public partial class PlayerModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private int _index = idx;
        public int Index
         {
            get => _index;
            set
            {
                if (Equals(value, _index)) return;
                _index = value;
                OnPropertyChanged(nameof(Index));
             }
         }

        private int _citiesPlayed;
        public int CitiesPlayed
         {
            get => _citiesPlayed;
            set
            {
                if (Equals(value, _citiesPlayed)) return;
                _citiesPlayed = value;
                OnPropertyChanged(nameof(CitiesPlayed));
             }
         }

        private int _knightsPlayed = 0;
        public int KnightsPlayed
         {
            get => _knightsPlayed;
            set
            {
                if (Equals(value, _knightsPlayed)) return;
                _knightsPlayed = value;
                OnPropertyChanged(nameof(KnightsPlayed));
             }
         }

        private int _goldRolls = 0;
        public int GoldRolls
         {
            get => _goldRolls;
            set
            {
                if (Equals(value, _goldRolls)) return;
                _goldRolls = value;
                OnPropertyChanged(nameof(GoldRolls));
             }
         }

        private bool _goodRoll = false;
        public bool GoodRoll
         {
            get => _goodRoll;
            set
            {
                if (Equals(value, _goodRoll)) return;
                _goodRoll = value;
                OnPropertyChanged(nameof(GoodRoll));
             }
         }

        private bool _hasLongestRoad = false;
        public bool HasLongestRoad
         {
            get => _hasLongestRoad;
            set
            {
                if (Equals(value, _hasLongestRoad)) return;
                _hasLongestRoad = value;
                OnPropertyChanged(nameof(HasLongestRoad));
             }
         }

        private bool _isCurrentPlayer = false;
        public bool IsCurrentPlayer
         {
            get => _isCurrentPlayer;
            set
            {
                if (Equals(value, _isCurrentPlayer)) return;
                _isCurrentPlayer = value;
                OnPropertyChanged(nameof(IsCurrentPlayer));
             }
         }

        private int _islandsPlayed;
        public int IslandsPlayed
         {
            get => _islandsPlayed;
            set
            {
                if (Equals(value, _islandsPlayed)) return;
                _islandsPlayed = value;
                OnPropertyChanged(nameof(IslandsPlayed));
             }
         }

        private bool _largestArmy = false;
        public bool LargestArmy
         {
            get => _largestArmy;
            set
            {
                if (Equals(value, _largestArmy)) return;
                _largestArmy = value;
                OnPropertyChanged(nameof(LargestArmy));
             }
         }

        private int _longestRoad;
        public int LongestRoad
         {
            get => _longestRoad;
            set
            {
                if (Equals(value, _longestRoad)) return;
                _longestRoad = value;
                OnPropertyChanged(nameof(LongestRoad));
             }
         }

        private int _maxNoResourceRolls = 0;
        public int MaxNoResourceRolls
         {
            get => _maxNoResourceRolls;
            set
            {
                if (Equals(value, _maxNoResourceRolls)) return;
                _maxNoResourceRolls = value;
                OnPropertyChanged(nameof(MaxNoResourceRolls));
             }
         }

        private int _noResourceCount = 0;
        public int NoResourceCount
         {
            get => _noResourceCount;
            set
            {
                if (Equals(value, _noResourceCount)) return;
                _noResourceCount = value;
                OnPropertyChanged(nameof(NoResourceCount));
             }
         }

        private int _pips = 0;
        public int Pips
         {
            get => _pips;
            set
            {
                if (Equals(value, _pips)) return;
                _pips = value;
                OnPropertyChanged(nameof(Pips));
             }
         }

        private int _roadsPlayed;
        public int RoadsPlayed
         {
            get => _roadsPlayed;
            set
            {
                if (Equals(value, _roadsPlayed)) return;
                _roadsPlayed = value;
                OnPropertyChanged(nameof(RoadsPlayed));
             }
         }

        private int _score;
        public int Score
         {
            get => _score;
            set
            {
                if (Equals(value, _score)) return;
                _score = value;
                OnPropertyChanged(nameof(Score));
             }
         }

        private int _settlementsPlayed;
        public int SettlementsPlayed
         {
            get => _settlementsPlayed;
            set
            {
                if (Equals(value, _settlementsPlayed)) return;
                _settlementsPlayed = value;
                OnPropertyChanged(nameof(SettlementsPlayed));
             }
         }

        private int _shipsPlayed;
        public int ShipsPlayed
         {
            get => _shipsPlayed;
            set
            {
                if (Equals(value, _shipsPlayed)) return;
                _shipsPlayed = value;
                OnPropertyChanged(nameof(ShipsPlayed));
             }
         }

        private int _timesTargeted;
        public int TimesTargeted
         {
            get => _timesTargeted;
            set
            {
                if (Equals(value, _timesTargeted)) return;
                _timesTargeted = value;
                OnPropertyChanged(nameof(TimesTargeted));
             }
         }


        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
