
using System.Collections.Generic;
using Catan10.Models;
using CommunityToolkit.Mvvm.ComponentModel;
using System.Linq;
using System.Collections.ObjectModel;
namespace Catan3.Models
{
    /// <summary>
    /// Represents the state of a player that is bound to the UI.
    /// </summary>
    public partial class PlayerModel : ObservableObject
    {
        /// <summary>
        /// Gets or sets the ID of the player.
        /// </summary>
        [ObservableProperty]
        public partial string Id { get; set; }

        /// <summary>
        /// Gets or sets the number of gold rolls.
        /// </summary>
        [ObservableProperty]
        public partial int GoldRolls { get; set; } = 0;

        /// <summary>
        /// Gets or sets the number of good rolls.
        /// </summary>
        [ObservableProperty]
        public partial int GoodRolls { get; set; } = 0;

        /// <summary>
        /// Gets or sets the number of bad rolls.
        /// </summary>
        [ObservableProperty]
        public partial int BadRolls { get; set; } = 0;

        /// <summary>
        /// Gets or sets a value indicating whether the player has the longest road.
        /// </summary>
        [ObservableProperty]
        public partial bool HasLongestRoad { get; set; } = false;

        /// <summary>
        /// Gets or sets the number of islands played.
        /// </summary>
        [ObservableProperty]
        public partial int IslandsPlayed { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the player has the largest army.
        /// </summary>
        [ObservableProperty]
        public partial bool LargestArmy { get; set; } = false;

        /// <summary>
        /// Gets or sets the length of the longest road.
        /// </summary>
        [ObservableProperty]
        public partial int LongestRoad { get; set; }

        /// <summary>
        /// Gets or sets the maximum number of no-resource rolls.
        /// </summary>
        [ObservableProperty]
        public partial int MaxNoResourceRolls { get; set; } = 0;

        /// <summary>
        /// Gets or sets the count of no-resource rolls.
        /// </summary>
        [ObservableProperty]
        public partial int NoResourceCount { get; set; } = 0;

        /// <summary>
        /// Gets or sets the number of stars.
        /// </summary>
        [ObservableProperty]
        public partial int Stars { get; set; } = 0;

        /// <summary>
        /// Gets or sets the score of the player.
        /// </summary>
        [ObservableProperty]
        public partial int Score { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the player has the highest score.
        /// </summary>
        [ObservableProperty]
        public partial bool HighestScore { get; set; } = false;

        /// <summary>
        /// Gets or sets the number of times the player has been targeted.
        /// </summary>
        [ObservableProperty]
        public partial int TimesTargeted { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the player is participating in the supplemental phase.
        /// </summary>
        [ObservableProperty]
        public partial bool ParticipatingInSupplemental { get; set; }


        /// <summary>
        /// Gets or sets a value indicating whether the player has completed their supplmentmental turn.
        /// This is used to know when to end the s  
        /// </summary>
        [ObservableProperty]
        public partial bool FinishedSuplemental { get; set; }

        /// <summary>
        /// Gets or sets the resources obtained by the player this turn.
        /// </summary>
        [ObservableProperty]
        public partial ResourcesModel ResourcesThisTurn { get; set; } = new();

        /// <summary>
        /// Gets or sets the aggregate value of all resources generated by the player.
        /// </summary>
        [ObservableProperty]
        public partial ResourcesModel ResourcesThisGame { get; set; } = new();

        /// <summary>
        /// Gets or sets the collection of unspent entitlements.
        /// </summary>
        [ObservableProperty]
        public partial ObservableCollection<Entitlement> UnspentEntitlements { get; set; } = [];

        /// <summary>
        /// Gets or sets the collection of entitlements spent in this game.
        /// </summary>
        [ObservableProperty]
        public partial ObservableCollection<Entitlement> SpentEntitlementsThisGame { get; set; } = [];

        /// <summary>
        /// Gets or sets the collection of entitlements spent in this turn.
        /// </summary>
        [ObservableProperty]
        public partial ObservableCollection<Entitlement> SpentEntitlementsThisTurn { get; set; } = [];

        /// <summary>
        /// Gets or sets the collection of Harbors owned by the player.
        /// </summary>
        [ObservableProperty]
        public partial ObservableCollection<HarborKey> OwnedHarbors { get; set; } = [];

        /// <summary>
        /// Gets the default instance of the PlayerModel class.
        /// </summary>
        public static PlayerModel Default { get; } = new PlayerModel("Nameless-001");

        /// <summary>
        /// Initializes a new instance of the PlayerModel class with the specified ID.
        /// </summary>
        /// <param name="id">The ID of the player.</param>
        public PlayerModel(string id)
        {
            Id = id;
        }

        /// <summary>
        /// Initializes a new instance of the PlayerModel class with a default ID.
        /// </summary>
        private PlayerModel()
        {
            Id = "Nameless-002";
        }

        /// <summary>
        /// Returns a string representation of the PlayerModel.
        /// </summary>
        /// <returns>A string representing the ID of the player.</returns>
        public override string ToString()
        {
            return $"{Id}";
        }
    }
    /// <summary>
    /// Provides extension methods for the PlayerModel class.
    /// </summary>
    public static class PlayerModelExtensions
    {
        /// <summary>
        /// Retrieves a PlayerModel from the collection by its ID.
        /// </summary>
        /// <param name="collection">The collection of PlayerModel instances.</param>
        /// <param name="id">The ID of the player to retrieve.</param>
        /// <returns>The PlayerModel with the specified ID, or null if not found.</returns>
        public static PlayerModel? PlayerFromId(this IList<PlayerModel> collection, string id)
        {
            return collection.FirstOrDefault((p) => p.Id == id);
        }
    }
}
