using System;
using Catan3.Shared.Utility;

namespace Catan3.Shared.Models
{
    /// <summary>
    /// Represents a building model in the game, including its key, state, and ownership information.
    /// Implements IComparable for sorting and comparison purposes.
    /// </summary>
    public class BuildingModel : IComparable<BuildingModel>
    {
        /// <summary>
        /// Initializes a new instance of the BuildingModel class with default values.
        /// </summary>
        public BuildingModel() : this(new BuildingKey { HexCoordinates = HexCoordinates.Default, Position = HexPosition.None }, BuildingState.NotBuildable)
        {
        }

        /// <summary>
        /// Initializes a new instance of the BuildingModel class with the specified building key and state.
        /// </summary>
        /// <param name="buildingKey">The key identifying the building's location and position.</param>
        /// <param name="buildingState">The state of the building.</param>
        public BuildingModel(BuildingKey buildingKey, BuildingState buildingState)
        {
            BuildingKey = buildingKey;
            BuildingState = buildingState;
        }

        /// <summary>
        /// Gets or sets the key identifying the building's location and position.
        /// </summary>
        public BuildingKey BuildingKey { get; set; } = new();

        /// <summary>
        /// Gets or sets the state of the building.
        /// </summary>
        public BuildingState BuildingState { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the building has a wall.
        /// </summary>
        public bool Wall { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether the building is a metropolis.
        /// </summary>
        public bool Metropolis { get; set; } = false;

        /// <summary>
        /// Gets or sets the ID of the owner of the building.
        /// </summary>
        public string? OwnerId { get; set; } = null;

        /// <summary>
        /// Gets the default instance of the BuildingModel class.
        /// </summary>
        public static BuildingModel Default { get; } = new();

        /// <summary>
        /// Compares the current BuildingModel with another BuildingModel.
        /// </summary>
        /// <param name="other">The BuildingModel to compare with the current BuildingModel.</param>
        /// <returns>A value that indicates the relative order of the BuildingModels being compared.</returns>
        public int CompareTo(BuildingModel? other)
        {
            if (other is null) return 1;
            return BuildingKey.CompareTo(other.BuildingKey);
        }

        /// <summary>
        /// Returns a string representation of the BuildingModel.
        /// </summary>
        /// <returns>A string in the format "BuildingKey-BuildingState-OwnerId".</returns>
        public override string? ToString() => $"{BuildingKey}-{BuildingState}-{OwnerId}";

        /// <summary>
        /// Calculates the resources generated by this building for a given resource type
        /// </summary>
        /// <param name="resourceType">The type of resource being generated</param>
        /// <returns>A ResourcesModel containing the generated resources</returns>
        public ResourcesModel Resources(ResourceType resourceType)
        {
            var resources = new ResourcesModel() ?? throw new GameException("small memory allocation must succeed");
            switch (resourceType)
            {
                case ResourceType.Wheat:
                    resources.Wheat = BuildingState == BuildingState.City ? 2 : 1;
                    break;
                case ResourceType.Wood:
                    resources.Wood = BuildingState == BuildingState.City ? 2 : 1;
                    break;
                case ResourceType.Sheep:
                    resources.Sheep = BuildingState == BuildingState.City ? 2 : 1;
                    break;
                case ResourceType.Brick:
                    resources.Brick = BuildingState == BuildingState.City ? 2 : 1;
                    break;
                case ResourceType.Ore:
                    resources.Ore = BuildingState == BuildingState.City ? 2 : 1;
                    break;
                case ResourceType.GoldMine:
                    resources.GoldMine = BuildingState == BuildingState.City ? 2 : 1;
                    break;
                case ResourceType.Robber:
                    resources.Robber = BuildingState == BuildingState.City ? 2 : 1;
                    break;
            }
            return resources;
        }
    }
}