using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using CommunityToolkit.Mvvm.ComponentModel;

namespace Catan3.Shared.Models
{
    /// <summary>
    /// Represents the state of a player that is bound to the UI.
    /// Supports both plain object usage (for JSON/API) and MVVM usage (for UI data binding).
    /// </summary>
    public partial class PlayerModel : ObservableObject
    {
        /// <summary>
        /// Gets or sets the ID of the player.
        /// </summary>
        [ObservableProperty]
        private string _id = string.Empty;

        /// <summary>
        /// Gets the display name of the player extracted from the ID.
        /// Follows Desktop app pattern: "Joe-001" ? "Joe"
        /// </summary>
        public string Name => ExtractNameFromId(Id);

        /// <summary>
        /// Gets or sets the number of gold rolls.
        /// </summary>
        [ObservableProperty]
        private int _goldRolls = 0;

        /// <summary>
        /// Gets or sets the number of good rolls.
        /// </summary>
        [ObservableProperty]
        private int _goodRolls = 0;

        /// <summary>
        /// Gets or sets the number of bad rolls.
        /// </summary>
        [ObservableProperty]
        private int _badRolls = 0;

        /// <summary>
        /// Gets or sets a value indicating whether the player has the longest road.
        /// </summary>
        [ObservableProperty]
        private bool _hasLongestRoad = false;

        /// <summary>
        /// Gets or sets the number of islands played.
        /// </summary>
        [ObservableProperty]
        private int _islandsPlayed;

        /// <summary>
        /// Gets or sets a value indicating whether the player has the largest army.
        /// </summary>
        [ObservableProperty]
        private bool _largestArmy = false;

        /// <summary>
        /// Gets or sets the length of the longest road.
        /// </summary>
        [ObservableProperty]
        private int _longestRoad;

        /// <summary>
        /// Gets or sets the maximum number of no-resource rolls.
        /// </summary>
        [ObservableProperty]
        private int _maxNoResourceRolls = 0;

        /// <summary>
        /// Gets or sets the count of no-resource rolls.
        /// </summary>
        [ObservableProperty]
        private int _noResourceCount = 0;

        /// <summary>
        /// Gets or sets the number of stars.
        /// </summary>
        [ObservableProperty]
        private int _stars = 0;

        /// <summary>
        /// Gets or sets the score of the player.
        /// </summary>
        [ObservableProperty]
        private int _score;

        /// <summary>
        /// Gets or sets a value indicating whether the player has the highest score.
        /// </summary>
        [ObservableProperty]
        private bool _highestScore = false;

        /// <summary>
        /// Gets or sets the number of times the player has been targeted.
        /// </summary>
        [ObservableProperty]
        private int _timesTargeted;

        /// <summary>
        /// Gets or sets a value indicating whether the player is participating in the supplemental phase.
        /// </summary>
        [ObservableProperty]
        private bool _participatingInSupplemental;

        /// <summary>
        /// Gets or sets a value indicating whether the player has completed their supplemental turn.
        /// </summary>
        [ObservableProperty]
        private bool _finishedSuplemental;

        /// <summary>
        /// Gets or sets the resources obtained by the player this turn.
        /// </summary>
        [ObservableProperty]
        private ResourcesModel _resourcesThisTurn = new();

        /// <summary>
        /// Gets or sets the aggregate value of all resources generated by the player.
        /// </summary>
        [ObservableProperty]
        private ResourcesModel _resourcesThisGame = new();

        /// <summary>
        /// Gets or sets the collection of unspent entitlements.
        /// </summary>
        [ObservableProperty]
        private List<Entitlement> _unspentEntitlements = [];

        /// <summary>
        /// Gets or sets the collection of entitlements spent in this game.
        /// </summary>
        [ObservableProperty]
        private List<Entitlement> _spentEntitlementsThisGame = [];

        /// <summary>
        /// Gets or sets the collection of entitlements spent in this turn.
        /// </summary>
        [ObservableProperty]
        private List<Entitlement> _spentEntitlementsThisTurn = [];

        /// <summary>
        /// Gets or sets the collection of Harbors owned by the player.
        /// </summary>
        public List<HarborKey> OwnedHarbors { get; set; } = [];

        /// <summary>
        /// Initializes a new instance of the PlayerModel class with the specified ID.
        /// </summary>
        /// <param name="id">The ID of the player.</param>
        public PlayerModel(string id)
        {
            Id = id;
        }

        /// <summary>
        /// Initializes a new instance of the PlayerModel class with a default ID.
        /// </summary>
        public PlayerModel()
        {
            Id = "Nameless-002";
        }

        /// <summary>
        /// Returns a string representation of the PlayerModel.
        /// </summary>
        /// <returns>A string representing the ID of the player.</returns>
        public override string ToString()
        {
            return $"{Id}";
        }

        /// <summary>
        /// Extracts display name from player ID following Desktop app pattern.
        /// "Joe-001" ? "Joe"
        /// </summary>
        /// <param name="id">The player ID to extract the name from</param>
        /// <returns>The extracted display name</returns>
        private static string ExtractNameFromId(string id)
        {
            if (string.IsNullOrEmpty(id)) return "Unknown";
            
            // Desktop app pattern: "Joe-001" -> "Joe"
            if (id.Contains('-'))
            {
                var parts = id.Split('-');
                if (parts.Length >= 2)
                {
                    return parts[0];
                }
            }
            
            return id;
        }
    }

   

   
}