using CommunityToolkit.Mvvm.ComponentModel;

namespace Catan3.Shared.Models
{
    /// <summary>
    /// Represents the state of a player that is bound to the UI.
    /// Supports both plain object usage (for JSON/API) and MVVM usage (for UI data binding).
    /// </summary>
    public partial class PlayerModel : ObservableObject
    {
        /// <summary>
        /// Gets or sets the ID of the player.
        /// </summary>
        [ObservableProperty]
        public partial string Id { get; set; } = string.Empty;

        // NOTE: There is deliberately no Name property here. A display name is identity data
        // owned by PlayerProfile, not game state, and it must never be derived from the ID --
        // parsing the ID produced a GUID fragment for any player whose ID was not "Name-NNN"
        // (issue #208). Resolve names from the profile by Id instead.

        /// <summary>
        /// Gets or sets the number of gold rolls.
        /// </summary>
        [ObservableProperty]
        public partial int GoldRolls { get; set; } = 0;

        /// <summary>
        /// Gets or sets the number of good rolls.
        /// </summary>
        [ObservableProperty]
        public partial int GoodRolls { get; set; } = 0;

        /// <summary>
        /// Gets or sets the number of bad rolls.
        /// </summary>
        [ObservableProperty]
        public partial int BadRolls { get; set; } = 0;

        /// <summary>
        /// Gets or sets a value indicating whether the player has the longest road.
        /// </summary>
        [ObservableProperty]
        public partial bool HasLongestRoad { get; set; } = false;

        /// <summary>
        /// Gets or sets the number of islands played.
        /// </summary>
        [ObservableProperty]
        public partial int IslandsPlayed { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the player has the largest army.
        /// </summary>
        [ObservableProperty]
        public partial bool LargestArmy { get; set; } = false;

        /// <summary>
        /// Gets or sets the length of the longest road.
        /// </summary>
        [ObservableProperty]
        public partial int LongestRoad { get; set; }

        /// <summary>
        /// Gets or sets the maximum number of no-resource rolls.
        /// </summary>
        [ObservableProperty]
        public partial int MaxNoResourceRolls { get; set; } = 0;

        /// <summary>
        /// Gets or sets the count of no-resource rolls.
        /// </summary>
        [ObservableProperty]
        public partial int NoResourceCount { get; set; } = 0;

        /// <summary>
        /// Gets or sets the number of stars.
        /// </summary>
        [ObservableProperty]
        public partial int Stars { get; set; } = 0;

        /// <summary>
        /// Gets or sets the score of the player.
        /// </summary>
        [ObservableProperty]
        public partial int Score { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the player has the highest score.
        /// </summary>
        [ObservableProperty]
        public partial bool HighestScore { get; set; } = false;

        /// <summary>
        /// Gets or sets the number of times the player has been targeted.
        /// </summary>
        [ObservableProperty]
        public partial int TimesTargeted { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the player is participating in the supplemental phase.
        /// </summary>
        [ObservableProperty]
        public partial bool ParticipatingInSupplemental { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the player has completed their supplemental turn.
        /// </summary>
        [ObservableProperty]
        public partial bool FinishedSupplemental { get; set; }

        /// <summary>
        /// Gets or sets the resources obtained by the player this turn.
        /// </summary>
        [ObservableProperty]
        public partial ResourcesModel ResourcesThisTurn { get; set; } = new();

        /// <summary>
        /// Gets or sets the aggregate value of all resources generated by the player.
        /// </summary>
        [ObservableProperty]
        public partial ResourcesModel ResourcesThisGame { get; set; } = new();

        /// <summary>
        /// Gets or sets the collection of unspent entitlements.
        /// </summary>
        [ObservableProperty]
        public partial List<Entitlement> UnspentEntitlements { get; set; } = [];

        /// <summary>
        /// Gets or sets the collection of entitlements spent in this game.
        /// </summary>
        [ObservableProperty]
        public partial List<Entitlement> SpentEntitlementsThisGame { get; set; } = [];

        /// <summary>
        /// Gets or sets the collection of entitlements spent in this turn.
        /// </summary>
        [ObservableProperty]
        public partial List<Entitlement> SpentEntitlementsThisTurn { get; set; } = [];

        /// <summary>
        /// Gets or sets the collection of Harbors owned by the player.
        /// </summary>
        public List<HarborKey> OwnedHarbors { get; set; } = [];

        /// <summary>
        /// Gets or sets the Victory Point card count entered at game end.
        /// This is manually entered when the winner is declared, as VP dev cards are kept secret.
        /// </summary>
        [ObservableProperty]
        public partial int VictoryPointCards { get; set; } = 0;

        /// <summary>
        /// Initializes a new instance of the PlayerModel class with the specified ID.
        /// </summary>
        /// <param name="id">The ID of the player.</param>
        public PlayerModel(string id)
        {
            Id = id;
        }

        /// <summary>
        /// Initializes a new instance of the PlayerModel class with a default ID.
        /// </summary>
        public PlayerModel()
        {
            Id = "Nameless-002";
        }

        /// <summary>
        /// Returns a string representation of the PlayerModel.
        /// </summary>
        /// <returns>A string representing the ID of the player.</returns>
        public override string ToString()
        {
            return $"{Id}";
        }

    }




}