using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;

namespace Catan3.Shared.Models
{
    /// <summary>
    /// Represents the state of a player that is bound to the UI.
    /// </summary>
    public class PlayerModel
    {
        /// <summary>
        /// Gets or sets the ID of the player.
        /// </summary>
        public string Id { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the number of gold rolls.
        /// </summary>
        public int GoldRolls { get; set; } = 0;

        /// <summary>
        /// Gets or sets the number of good rolls.
        /// </summary>
        public int GoodRolls { get; set; } = 0;

        /// <summary>
        /// Gets or sets the number of bad rolls.
        /// </summary>
        public int BadRolls { get; set; } = 0;

        /// <summary>
        /// Gets or sets a value indicating whether the player has the longest road.
        /// </summary>
        public bool HasLongestRoad { get; set; } = false;

        /// <summary>
        /// Gets or sets the number of islands played.
        /// </summary>
        public int IslandsPlayed { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the player has the largest army.
        /// </summary>
        public bool LargestArmy { get; set; } = false;

        /// <summary>
        /// Gets or sets the length of the longest road.
        /// </summary>
        public int LongestRoad { get; set; }

        /// <summary>
        /// Gets or sets the maximum number of no-resource rolls.
        /// </summary>
        public int MaxNoResourceRolls { get; set; } = 0;

        /// <summary>
        /// Gets or sets the count of no-resource rolls.
        /// </summary>
        public int NoResourceCount { get; set; } = 0;

        /// <summary>
        /// Gets or sets the number of stars.
        /// </summary>
        public int Stars { get; set; } = 0;

        /// <summary>
        /// Gets or sets the score of the player.
        /// </summary>
        public int Score { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the player has the highest score.
        /// </summary>
        public bool HighestScore { get; set; } = false;

        /// <summary>
        /// Gets or sets the number of times the player has been targeted.
        /// </summary>
        public int TimesTargeted { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the player is participating in the supplemental phase.
        /// </summary>
        public bool ParticipatingInSupplemental { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the player has completed their supplemental turn.
        /// </summary>
        public bool FinishedSuplemental { get; set; }

        /// <summary>
        /// Gets or sets the resources obtained by the player this turn.
        /// </summary>
        public ResourcesModel ResourcesThisTurn { get; set; } = new();

        /// <summary>
        /// Gets or sets the aggregate value of all resources generated by the player.
        /// </summary>
        public ResourcesModel ResourcesThisGame { get; set; } = new();

        /// <summary>
        /// Gets or sets the collection of unspent entitlements.
        /// </summary>
        public List<Entitlement> UnspentEntitlements { get; set; } = [];

        /// <summary>
        /// Gets or sets the collection of entitlements spent in this game.
        /// </summary>
        public List<Entitlement> SpentEntitlementsThisGame { get; set; } = [];

        /// <summary>
        /// Gets or sets the collection of entitlements spent in this turn.
        /// </summary>
        public List<Entitlement> SpentEntitlementsThisTurn { get; set; } = [];

        /// <summary>
        /// Gets or sets the collection of Harbors owned by the player.
        /// </summary>
        public List<HarborKey> OwnedHarbors { get; set; } = [];

        /// <summary>
        /// Initializes a new instance of the PlayerModel class with the specified ID.
        /// </summary>
        /// <param name="id">The ID of the player.</param>
        public PlayerModel(string id)
        {
            Id = id;
        }

        /// <summary>
        /// Initializes a new instance of the PlayerModel class with a default ID.
        /// </summary>
        public PlayerModel()
        {
            Id = "Nameless-002";
        }

        /// <summary>
        /// Returns a string representation of the PlayerModel.
        /// </summary>
        /// <returns>A string representing the ID of the player.</returns>
        public override string ToString()
        {
            return $"{Id}";
        }
    }

    /// <summary>
    /// Provides extension methods for the PlayerModel class.
    /// </summary>
    public static class PlayerModelExtensions
    {
        /// <summary>
        /// Retrieves a PlayerModel from the collection by its ID.
        /// </summary>
        /// <param name="collection">The collection of PlayerModel instances.</param>
        /// <param name="id">The ID of the player to retrieve.</param>
        /// <returns>The PlayerModel with the specified ID, or null if not found.</returns>
        public static PlayerModel? PlayerFromId(this IList<PlayerModel> collection, string id)
        {
            return collection.FirstOrDefault((p) => p.Id == id);
        }
    }

   
}