/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Buildings/BuildingKey.model.json
    code gen version  = 5
    model version     = 2

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;
using Catan3.Utility;

namespace Catan3.Models
{
    public partial class BuildingKey : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private HexCoordinates _hexCoordinates;
        public HexCoordinates HexCoordinates
         {
            get => _hexCoordinates;
            set
            {
                if (Equals(value, _hexCoordinates)) return;
                _hexCoordinates = value;
                OnPropertyChanged(nameof(HexCoordinates));
             }
         }

        private HexPosition _position;
        public HexPosition Position
         {
            get => _position;
            set
            {
                if (Equals(value, _position)) return;
                _position = value;
                OnPropertyChanged(nameof(Position));
             }
         }


        public BuildingKey(HexCoordinates hexcoordinates, HexPosition position)
        {
            _hexCoordinates = hexcoordinates;
            _position = position;
        }

        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
