/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Buildings/BuildingViewModel.model.json
    code gen version  = 5
    model version     = 2

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;
using Microsoft.UI;
using Microsoft.UI.Xaml.Media;

namespace Catan3.Models
{
    public partial class BuildingViewModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private BuildingModel _building;
        public BuildingModel Building
         {
            get => _building;
            set
            {
                if (Equals(value, _building)) return;
                _building = value;
                OnPropertyChanged(nameof(Building));
             }
         }

        private BoardLayout _layout;
        public BoardLayout Layout
         {
            get => _layout;
            set
            {
                if (Equals(value, _layout)) return;
                _layout = value;
                OnPropertyChanged(nameof(Layout));
             }
         }

        private double _left;
        public double Left
         {
            get => _left;
            set
            {
                if (Equals(value, _left)) return;
                _left = value;
                OnPropertyChanged(nameof(Left));
             }
         }

        private double _top;
        public double Top
         {
            get => _top;
            set
            {
                if (Equals(value, _top)) return;
                _top = value;
                OnPropertyChanged(nameof(Top));
             }
         }

        private int _stars = 0;
        public int Stars
         {
            get => _stars;
            set
            {
                if (Equals(value, _stars)) return;
                _stars = value;
                OnPropertyChanged(nameof(Stars));
             }
         }

        private Brush? _background = BrushCache.GetSolidColorBrush(Colors.Transparent);
        public Brush? Background
         {
            get => _background;
            set
            {
                if (Equals(value, _background)) return;
                _background = value;
                OnPropertyChanged(nameof(Background));
             }
         }

        private Brush? _foreground = BrushCache.GetSolidColorBrush(Colors.Transparent);
        public Brush? Foreground
         {
            get => _foreground;
            set
            {
                if (Equals(value, _foreground)) return;
                _foreground = value;
                OnPropertyChanged(nameof(Foreground));
             }
         }


        public BuildingViewModel(BuildingModel building, BoardLayout layout)
        {
            _building = building;
            _layout = layout;
            Init();
        }

        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
