/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Roads/RoadKey.model.json
    code gen version  = 5
    model version     = 2

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;
using Catan3.Utility;

namespace Catan3.Models
{
    public partial class RoadKey : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private HexCoordinates _tileKey = tileKey;
        public HexCoordinates TileKey
         {
            get => _tileKey;
            set
            {
                if (Equals(value, _tileKey)) return;
                _tileKey = value;
                OnPropertyChanged(nameof(TileKey));
             }
         }

        private HexSide _hexSide = position;
        public HexSide HexSide
         {
            get => _hexSide;
            set
            {
                if (Equals(value, _hexSide)) return;
                _hexSide = value;
                OnPropertyChanged(nameof(HexSide));
             }
         }


        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
