/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Roads/RoadViewModel.model.json
    code gen version  = 5
    model version     = 1.0b

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;
using Microsoft.UI;
using Microsoft.UI.Xaml.Media;

namespace Catan3.Models
{
    public partial class RoadViewModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private RoadModel _road;
        public RoadModel Road
         {
            get => _road;
            set
            {
                if (Equals(value, _road)) return;
                _road = value;
                OnPropertyChanged(nameof(Road));
             }
         }

        private BoardLayout _layout;
        public BoardLayout Layout
         {
            get => _layout;
            set
            {
                if (Equals(value, _layout)) return;
                _layout = value;
                OnPropertyChanged(nameof(Layout));
             }
         }

        private PlayerViewModel? _owner = null;
        public PlayerViewModel? Owner
         {
            get => _owner;
            set
            {
                if (Equals(value, _owner)) return;
                _owner = value;
                OnPropertyChanged(nameof(Owner));
             }
         }

        private Brush _background = BrushCache.GetSolidColorBrush(Colors.Transparent);
        public Brush Background
         {
            get => _background;
            set
            {
                if (Equals(value, _background)) return;
                _background = value;
                OnPropertyChanged(nameof(Background));
             }
         }

        private Brush _foreground = BrushCache.GetSolidColorBrush(Colors.Transparent);
        public Brush Foreground
         {
            get => _foreground;
            set
            {
                if (Equals(value, _foreground)) return;
                _foreground = value;
                OnPropertyChanged(nameof(Foreground));
             }
         }

        private double _left;
        public double Left
         {
            get => _left;
            set
            {
                if (Equals(value, _left)) return;
                _left = value;
                OnPropertyChanged(nameof(Left));
             }
         }

        private double _top;
        public double Top
         {
            get => _top;
            set
            {
                if (Equals(value, _top)) return;
                _top = value;
                OnPropertyChanged(nameof(Top));
             }
         }

        private double _index;
        public double Index
         {
            get => _index;
            set
            {
                if (Equals(value, _index)) return;
                _index = value;
                OnPropertyChanged(nameof(Index));
             }
         }


        public RoadViewModel(RoadModel road, BoardLayout layout)
        {
            _road = road;
            _layout = layout;
            Init();
        }

        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
