/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Roads/RoadModel.model.json
    code gen version  = 5
    model version     = 2

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;

namespace Catan3.Models
{
    public partial class RoadModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private RoadKey _roadKey;
        public RoadKey RoadKey
         {
            get => _roadKey;
            set
            {
                if (Equals(value, _roadKey)) return;
                _roadKey = value;
                OnPropertyChanged(nameof(RoadKey));
             }
         }

        private RoadState _roadState = RoadState.Unowned;
        public RoadState RoadState
         {
            get => _roadState;
            set
            {
                if (Equals(value, _roadState)) return;
                _roadState = value;
                OnPropertyChanged(nameof(RoadState));
             }
         }

        private PlayerModel? _owner = null;
        public PlayerModel? Owner
         {
            get => _owner;
            set
            {
                if (Equals(value, _owner)) return;
                _owner = value;
                OnPropertyChanged(nameof(Owner));
             }
         }


        public RoadModel(RoadKey roadkey)
        {
            _roadKey = roadkey;
        }

        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
