/* WARNING: this is an autogenerated file.  Do Not edit directly.  Edit the /Models/models.json file instead */
using System.ComponentModel;
namespace Catan3.Models
{
    public partial class BuildingKey(BuildingPosition buildingPosition, TileKey tileKey) : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        public BuildingPosition BuildingPosition
        {
            get => buildingPosition;
            set
            {
                if (Equals(value, buildingPosition)) return;
                buildingPosition = value;
                OnPropertyChanged(nameof(BuildingPosition));
            }
        }
        public TileKey TileKey
        {
            get => tileKey;
            set
            {
                if (Equals(value, tileKey)) return;
                tileKey = value;
                OnPropertyChanged(nameof(TileKey));
            }
        }
        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
