<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <BlazorEnableDebugging>false</BlazorEnableDebugging>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebUI\Catan3.WebUI.csproj" />
  </ItemGroup>

  <Target Name="RemoveDebugProxy" AfterTargets="Publish">
    <RemoveDir Directories="$(PublishDir)BlazorDebugProxy" />
  </Target>

</Project>
