/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Robber/RobberViewModel.model.json
    code gen version  = 5
    model version     = 1

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;
using Catan3.Utility;

namespace Catan3.Models
{
    public partial class RobberViewModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private RobberModel _robberModel;
        public RobberModel RobberModel
         {
            get => _robberModel;
            set
            {
                if (Equals(value, _robberModel)) return;
                _robberModel = value;
                OnPropertyChanged(nameof(RobberModel));
             }
         }


        public RobberViewModel(RobberModel robbermodel)
        {
            _robberModel = robbermodel;
        }

        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
