/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Robber/Robber.model.json
    code gen version  = 5
    model version     = 2

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;
using Catan3.Utility;

namespace Catan3.Models
{
    public partial class RobberModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private HexCoordinates _coordinates = HexCoordinates.Default;
        public HexCoordinates Coordinates
         {
            get => _coordinates;
            set
            {
                if (Equals(value, _coordinates)) return;
                _coordinates = value;
                OnPropertyChanged(nameof(Coordinates));
             }
         }

        private string? _movedBy = null;
        public string? MovedBy
         {
            get => _movedBy;
            set
            {
                if (Equals(value, _movedBy)) return;
                _movedBy = value;
                OnPropertyChanged(nameof(MovedBy));
             }
         }

        private string? _targetted = null;
        public string? Targetted
         {
            get => _targetted;
            set
            {
                if (Equals(value, _targetted)) return;
                _targetted = value;
                OnPropertyChanged(nameof(Targetted));
             }
         }

        private int _resourcesStolen = 0;
        public int ResourcesStolen
         {
            get => _resourcesStolen;
            set
            {
                if (Equals(value, _resourcesStolen)) return;
                _resourcesStolen = value;
                OnPropertyChanged(nameof(ResourcesStolen));
             }
         }


        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
