/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Tiles/TileModel.model.json
    code gen version  = 5
    model version     = 3

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;
using Catan3.Utility;

namespace Catan3.Models
{
    public partial class TileModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private HexCoordinates _tileKey = HexCoordinates.Default;
        public HexCoordinates TileKey
         {
            get => _tileKey;
            set
            {
                if (Equals(value, _tileKey)) return;
                _tileKey = value;
                OnPropertyChanged(nameof(TileKey));
             }
         }

        private ResourceTileType _resourceTileType = ResourceTileType.None;
        public ResourceTileType ResourceTileType
         {
            get => _resourceTileType;
            set
            {
                if (Equals(value, _resourceTileType)) return;
                _resourceTileType = value;
                OnPropertyChanged(nameof(ResourceTileType));
             }
         }

        private int _number = 0;
        public int Number
         {
            get => _number;
            set
            {
                if (Equals(value, _number)) return;
                _number = value;
                OnPropertyChanged(nameof(Number));
                OnPropertyChanged(nameof(Stars));
             }
         }


        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
