/*
                           ** WARNING ** 

    This is an autogenerated file. Do not edit directly. Edit the json file instead.
    This file should *not be checked in* and should already be part of .gitignore

    template file     = file://D:/GitHub/Catan3
    model file        = file://D:/GitHub/Catan3/Tiles/TileViewModel.model.json
    code gen version  = 5
    model version     = 3

    to update the generated model, execute the .\update_models.bat file, or run the
    GenerateModels.tt Text Template. Both of these depend on the ModelGenerator project
    available at https://github.com/joelong01/ModelGenerator
*/

using System.ComponentModel;

namespace Catan3.Models
{
    public partial class TileViewModel : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler? PropertyChanged;
        private TileModel _tile;
        public TileModel Tile
         {
            get => _tile;
            set
            {
                if (Equals(value, _tile)) return;
                _tile = value;
                OnPropertyChanged(nameof(Tile));
             }
         }

        private BoardLayout? _layout = null;
        public BoardLayout? Layout
         {
            get => _layout;
            set
            {
                if (Equals(value, _layout)) return;
                _layout = value;
                OnPropertyChanged(nameof(Layout));
             }
         }

        private double _left = 110.0;
        public double Left
         {
            get => _left;
            set
            {
                if (Equals(value, _left)) return;
                _left = value;
                OnPropertyChanged(nameof(Left));
             }
         }

        private double _top = 200.0;
        public double Top
         {
            get => _top;
            set
            {
                if (Equals(value, _top)) return;
                _top = value;
                OnPropertyChanged(nameof(Top));
             }
         }

        private int _index = -1;
        public int Index
         {
            get => _index;
            set
            {
                if (Equals(value, _index)) return;
                _index = value;
                OnPropertyChanged(nameof(Index));
             }
         }

        private CatanOrientation _orientation = CatanOrientation.FaceDown;
        public CatanOrientation Orientation
         {
            get => _orientation;
            set
            {
                if (Equals(value, _orientation)) return;
                _orientation = value;
                OnPropertyChanged(nameof(Orientation));
             }
         }


        public TileViewModel(TileModel tile, BoardLayout? layout)
        {
            _tile = tile;
            _layout = layout;
            Init();
        }

        protected virtual void OnPropertyChanged(string propertyName) =>
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
}
